Feature/tzip 16
Cryptonomic/Conseil pull request #1014
Opened 2021-07-02 19:41 UTC by piotrkosecki

Resolves #999 

Implemented handling of the tzip-16 metadata fetching as described in the ticket.

2021-07-16 02:38 UTC, vishakh requested changes

2021-07-16 02:38 UTC, vishakh commented on sql/conseil.sql
> +    desctiption text,
Typo

2021-07-16 16:38 UTC, piotrkosecki commented on sql/conseil.sql
> +    desctiption text,
fixed

2021-07-27 14:44 UTC, vishakh requested changes

2021-07-27 14:44 UTC, vishakh commented on conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/MetadataProcessor.scala
> +class MetadataProcessor(
A comment explaining the purpose of this class and how it works would be very useful here.

2021-07-27 14:44 UTC, vishakh commented on conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/TokenContracts.scala
> +    private def proceduralDecode(hex: String): String = {
Please leave a note about the function here.

2021-07-27 14:44 UTC, vishakh commented on conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/Tzip16MetadataFetcher.scala
> +  def getHttpMetadataWithRegisteredTokensRow(
Please remove.

2021-07-27 14:44 UTC, vishakh commented on conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/Tzip16MetadataFetcher.scala
> +                  s"I encountered problems while fetching baking rights from TZIP-16 for blocks $showHashes. The error says ${err.getMessage}"
Fix please

2021-07-27 14:44 UTC, vishakh commented on conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/MetadataProcessor.scala
> +          println(metadata)
Remove please.

2021-07-30 17:28 UTC, vishakh approved these changes

2021-07-30 17:28 UTC, merged