Granada related fixes and updates.
Cryptonomic/Conseil pull request #1030
Opened 2021-08-12 14:23 UTC by piotrkosecki

This PR contains bunch of fixes related to the Granada upgrade:
1. Baking/endorsing rights update after main loop reaches the head(previously only `estimated_time` was updated)
2. Explicitly using config setting for tracing calls and `parsing.max-to-strict-bytes`(responsible for recent errors with request too large) and adding reading  those values from env variables
3. Adding renamed field `deposits` to `CycleBalance` case class so we will avoid some warnings(and keeping the original one so we will be backward compatible)

2021-08-24 11:17 UTC, SiddharthV1 approved these changes

2021-08-24 11:18 UTC, SiddharthV1 approved these changes

2021-09-14 14:16 UTC, vishakh requested changes

2021-09-14 14:16 UTC, vishakh commented on conseil-lorre/src/main/resources/logging.conf
> +            from-env: "LORRE_NODE_RPC_BATCH_LOG_LEVEL",
Let's document this.

2021-09-20 20:27 UTC, vishakh approved these changes

2021-09-20 20:27 UTC, merged